let book;

function setup() {
  createCanvas(500, 800);
  pixelDensity(3);
  textFont("Kode Mono");

  // createBook(widthInches, heightInches, totalPages)
  // or: createBook("A4", 50)
  // or: createBook(15, 20, 50, "cm")
  book = createBook(5, 8, 50);
  // book.setBleed(0.25); // optional — set bleed in inches (or cm if using cm mode)

  textAlign(LEFT, TOP);
}

function draw() {
  // draw normally — this is what you see on screen AND the trim content in the PDF
  background(0);

  fill("white");
  textSize(50);
  noStroke();

  if (book.page === 0) {
    // — cover page — bleed only on this page
    book.bleed.background(0);
    text("A Computational Book Generated By p5.js", 20, 20, width - 60);
    text("Created By\nMunus Shih", 20, height - 130, width - 40);
  } else if (book.page === book.totalPages - 1) {
    // — back page —
    text(
      "Created at\n" + new Date().toLocaleDateString(),
      20,
      height - 130,
      width - 40,
    );
  } else {
    // — inner pages —
    text("Page " + book.pageNumber, 20, 20, width - 40);

    noFill();
    stroke(255);
    strokeWeight(1);
    translate(width / 2, height / 2);

    let A = 100 + sin(book.progress * TWO_PI) * 200;
    let B = 100 + cos(book.progress * TWO_PI + 1000) * 200;

    let a = 0.5 + book.progress * 6;
    let b = 0.5 + book.progress * 4;
    let delta = book.progress * PI * 10;
    let cycles = constrain(5 + book.progress * 15, 5, 20);

    beginShape();
    for (let theta = 0; theta < TWO_PI * cycles; theta += 0.01) {
      let x = A * sin(a * theta + delta);
      let y = B * cos(b * theta + delta);
      vertex(x, y);
    }
    endShape();
  }

  // capture this frame as a page — PDF saves automatically on the last page
  book.addPage();
}
